[tool.poetry]
name = "photos-api"
version = "0.1.0"
description = "A Fast API based API"
authors = ["Ugo Okoroafor <39538470+Uokoroafor@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
annotated-types = "0.6.0"
anyio = "3.7.1"
click = "8.1.7"
exceptiongroup = "1.2.0"
fastapi = "0.104.1"
h11 = "0.14.0"
httptools = "0.6.1"
idna = "3.6"
pydantic = "2.5.2"
pydantic-core = "2.14.5"
python-dotenv = "1.0.0"
pyyaml = "6.0.1"
sniffio = "1.3.0"
starlette = "0.27.0"
typing-extensions = "4.8.0"
uvicorn = "0.24.0.post1"
uvloop = "0.19.0"
watchfiles = "0.21.0"
websockets = "12.0"
build = "1.0.3"
cachecontrol = "0.13.1"
certifi = "2023.11.17"
cffi = "1.16.0"
charset-normalizer = "3.3.2"
cleo = "2.1.0"
coverage = "7.3.2"
crashtest = "0.4.1"
distlib = "0.3.7"
dulwich = "0.21.7"
fastjsonschema = "2.19.0"
filelock = "3.13.1"
importlib-metadata = "7.0.0"
iniconfig = "2.0.0"
installer = "0.7.0"
jaraco-classes = "3.3.0"
keyring = "24.3.0"
more-itertools = "10.1.0"
msgpack = "1.0.7"
packaging = "23.2"
pexpect = "4.9.0"
pkginfo = "1.9.6"
platformdirs = "3.11.0"
pluggy = "1.3.0"
poetry = "1.7.1"
poetry-core = "1.8.1"
poetry-plugin-export = "1.6.0"
ptyprocess = "0.7.0"
pycparser = "2.21"
pyproject-hooks = "1.0.0"
pytest = "7.4.3"
python-multipart = "0.0.6"
rapidfuzz = "3.5.2"
requests = "2.31.0"
requests-toolbelt = "1.0.0"
shellingham = "1.5.4"
tomli = "2.0.1"
tomlkit = "0.12.3"
trove-classifiers = "2023.11.29"
urllib3 = "2.1.0"
virtualenv = "20.25.0"
xattr = "0.10.1"
zipp = "3.17.0"
sqlalchemy = "^2.0.23"
psycopg2-binary = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
