name: Continuous Integration

# This workflow is triggered on every push to any branch in the repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with your Python version
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies with Poetry
      run: |
        poetry install
    - name: Run tests with pytest
      run: |
        poetry run pytest